---
- name: Magento 2 | Assets
  shell: '{{ magento_php_path }} {{ (ansistrano_release_path.stdout, magento_bin_path) | path_join }} setup:static-content:deploy --content-version={{content_version}} {{ magento_static_content_locales | join(" ") }} -j {{magento_static_content_jobs}}'
  register: assets
- debug:
        msg: "{{assets.stdout}}"