# Symlinks shared paths and files
- name: Magento 2 | Assets
  shell: '{{ php_bin }} {{ ansistrano_release_path.stdout }}/bin/magento setup:static-content:deploy --content-version={{content_version}} {{static_content_locales}} -j {{static_content_jobs}}'
  register: compile
  vars:
    php_bin: /usr/bin/php7.4
    content_version: 123456789
    static_content_locales: 'en_US fr_FR'
    static_content_jobs: 1
- debug:
        msg: "{{compile.stdout}}"

