---
- name: Magento 2 | Dump autoload
  shell: cd {{ ansistrano_release_path.stdout }} && {{ magento_php_path }} {{magento_composer_path}} dump-autoload -o
  register: autoload
- debug:
        msg: "{{autoload.stdout}}"