---
- name: Magento 2 | Compilation
  shell: '{{ magento_php_path }} {{ (ansistrano_release_path.stdout, magento_bin_path) | path_join }} setup:di:compile'
  register: compile
- debug:
        msg: "{{compile.stdout}}"