---
- name: Magento 2 | Check Config Import
  shell: '{{ magento_php_path }} {{ (ansistrano_release_path.stdout, magento_bin_path) | path_join }} app:config:status'
  register: check_config_import
  ignore_errors: True
  changed_when:
    - check_config_import.rc == 2

- import_tasks: "../../joris_ati4.ansistrano_magento_deploy/tasks/maintenance-enable.yml"
  when: check_config_import.rc == 2

- name: Magento 2 | Config Import
  shell: '{{ magento_php_path }} {{ (ansistrano_release_path.stdout, magento_bin_path) | path_join }} app:config:import --no-interaction'
  register: config_import
  when: check_config_import.rc == 2

- debug:
        msg: "{{config_import.stdout}}"

- import_tasks: "../../joris_ati4.ansistrano_magento_deploy/tasks/maintenance-disable.yml"
  when: check_config_import.rc == 2