---
- name: Magento 2 | Check Database Upgrade
  shell: '{{ magento_php_path }} {{ (ansistrano_release_path.stdout, magento_bin_path) | path_join }} setup:db:status'
  register: check_db_upgrade
  ignore_errors: True
  changed_when:
    - check_db_upgrade.rc == 2

- import_tasks: "../../joris_ati4.ansistrano_magento_deploy/tasks/maintenance-enable.yml"
  when: check_db_upgrade.rc == 2

- name: Magento 2 | Database Upgrade
  shell: '{{ magento_php_path }} {{ (ansistrano_release_path.stdout, magento_bin_path) | path_join }} setup:upgrade --keep-generated --no-interaction'
  register: db_upgrade
  when: check_db_upgrade.rc == 2

- debug:
        msg: "{{ db_upgrade.stdout }}"
  when: check_db_upgrade.rc == 2

- import_tasks: "../../joris_ati4.ansistrano_magento_deploy/tasks/maintenance-disable.yml"
  when: check_db_upgrade.rc == 2